---
- hosts: db
  vars:
    db_name: mailgenic
    db_deploy_user: deploy
    db_deploy_pass: passw√∂rd
    db_dovecot_user: dovecot
    db_dovecot_pass: 127lkasfb
    db_postfix_user: postfix
    db_postfix_pass: 12xfx_341
  roles:
    - db
#- hosts: mta
#  vars:
#    db_name: mailgenic
#    db_postfix_user: postfix
#    db_postfix_pass: 12xfx_341
#    mda_proxy_host: gamma
#    mda_proxy_port: 12345
#  roles:
#    - mta

